version: "3.9"

volumes:
  pgdata_keycloack:
  pgdata_app:

services:
  db_app:
    container_name: db_app
    image: library/postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata_app:/var/lib/postgresql/data
    #healtcheck:
    restart: unless-stopped

#  holiday:
#     container_name: holiday
#     build:
#        dockerfile: Dockerfile
#     image: holiday
#     ports:
#         - 8080:8080
#     depends_on:
#      - db_app    
#      - keycloak
#     environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_app:5432/appdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - SERVER_PORT=8080

  db_keycloak:
    container_name: db_keycloak
    image: library/postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak_db
    ports:
      - "5434:5432"
    volumes:
      - pgdata_keycloack:/var/lib/postgresql/data
    #healtcheck:
    restart: unless-stopped
    
  keycloak:
    container_name: keycloak
    image: jboss/keycloak    
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db_keycloak
      DB_DATABASE: keycloak_db
      DB_USER: postgres
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - db_keycloak
   