<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Welcome </title>
</head>
<body>
    <h1>Admin page</h1>
     <div>
                <form name="users_list" action="admin/userslist" method="GET">
                    <p> <input type="submit" value="Список пользователей" /> </p>
                </form>
             </div>
       <div>
              <p>
                <a href="/logout">Logout</a>
              </p>
         </div>
</body>
</html>