
<!DOCTYPE HTML>
<html>
   <head>
      <meta charset="UTF-8" />
      <title>Игровая сессия</title>
   </head>
   <body>
        <div>
            <fieldset>
                <legend>Установочные параметры сессии</legend>
                <form name="session properties" action="save" method="POST">

                    <input type="submit" value="Save" />
                </form>
            </fieldset>
        </div>
   </body>
</html>