<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>start session page</title>
</head>
<body>
    <h1>Statistic session page</h1>
      <div>
            <fieldset>
                <legend><h3>Новая сессия</h3></legend>
                    <form name="" action="back" method="GET">
                        <input type="submit" value="Назад" />
                    </form>
                </fieldset>
      </div>
</body>
</html>